version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cadastro_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgressql/data
volumes:
  postgres_data: {}